<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Samples.SecretKeyAuth.Direct</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Xg3.Auth" Version="0.1.0" />
  </ItemGroup>
</Project>
