<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Xg3.Auth.ClientIntegration.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Xg3.Auth\Xg3.Auth.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Refit" />
    <PackageReference Include="Flurl.Http" />
    <PackageReference Include="RestSharp" />
  </ItemGroup>
</Project>
